openapi: 3.0.1
info:
  title: posts
  description: API Definition of posts
  version: 1.0.0
servers:
- url: http://localhost:8290/placeposts
paths:
  /{postId}:
    get:
      parameters:
      - name: postId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
